#!/usr/bin/env node
/**
 * Generates docs/MAP.generated.md — the machine-checked half of the repo map (facts that go stale by hand):
 *   1. API routes (methods, guard flags)
 *   2. Reverse import index: for every source file, who imports it (and which tests cover it)
 *   3. Environment variables and where they are read
 *   4. Browser storage keys, custom events, server-side global holders and where they live
 *
 * The hand-written half (what things MEAN, change recipes, duplicated logic) is docs/MAP.md.
 *   node scripts/gen-map.mjs           write docs/MAP.generated.md
 *   node scripts/gen-map.mjs --check   exit 1 if it is out of date (bun run map:check)
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs'
import { join, relative, dirname, resolve } from 'node:path'

const ROOT = resolve(new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'))
const SRC = join(ROOT, 'src')
const OUT = join(ROOT, 'docs', 'MAP.generated.md')

const walk = (dir, out = []) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) walk(p, out)
    else if (/\.(ts|tsx)$/.test(e.name)) out.push(p)
  }
  return out
}
const rel = (p) => relative(ROOT, p).replace(/\\/g, '/')
const files = walk(SRC).sort()
const text = new Map(files.map((f) => [f, readFileSync(f, 'utf8')]))
const isTest = (f) => f.includes('/__tests__/') || /\.test\.tsx?$/.test(f)

// ---- 1. routes -------------------------------------------------------------------------------------------
const routes = files.filter((f) => f.endsWith('/route.ts')).map((f) => {
  const s = text.get(f)
  const methods = [...s.matchAll(/^export const (GET|POST|PUT|PATCH|DELETE) = guard\(([^\n]*)/gm)].map((m) => {
    const flags = []
    if (/privileged:\s*true/.test(m[2])) flags.push('privileged')
    if (/rateLimit:\s*false/.test(m[2])) flags.push('no-rate-limit')
    return m[1] + (flags.length ? ` (${flags.join(', ')})` : '')
  })
  const doc = (s.match(/^\s*\*\s*(?:v\d+[^:]*:\s*)?((?:GET|POST|PUT|DELETE)[^\n]*)/m) || s.match(/^\/\*\*\s*\n\s*\*\s*([^\n]+)/) || [])[1] || ''
  return { path: '/' + rel(f).replace(/^src\/app\//, '').replace(/\/route\.ts$/, ''), methods, doc: doc.replace(/\s+/g, ' ').trim().slice(0, 110), file: rel(f) }
})

// ---- 2. import graph -------------------------------------------------------------------------------------
const resolveImport = (from, spec) => {
  let base
  if (spec.startsWith('@/')) base = join(SRC, spec.slice(2))
  else if (spec.startsWith('.')) base = resolve(dirname(from), spec)
  else return null
  for (const c of [base + '.ts', base + '.tsx', join(base, 'index.ts'), join(base, 'index.tsx'), base]) {
    if (existsSync(c) && statSync(c).isFile() && text.has(c)) return c
  }
  return null
}
const importedBy = new Map(files.map((f) => [f, []]))
const importsOf = new Map()
for (const f of files) {
  const deps = new Set()
  for (const m of text.get(f).matchAll(/(?:import|export)\s[^'"]*?from\s+['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)/g)) {
    const r = resolveImport(f, m[1] || m[2])
    if (r && r !== f) deps.add(r)
  }
  importsOf.set(f, deps)
  for (const d of deps) importedBy.get(d).push(f)
}

// ---- 3/4. env vars, storage keys, events, holders ---------------------------------------------------------
const collect = (re, group = 1, only = () => true) => {
  const m = new Map()
  for (const f of files) {
    if (!only(f)) continue
    for (const x of text.get(f).matchAll(re)) {
      const k = x[group]
      if (!m.has(k)) m.set(k, new Set())
      m.get(k).add(rel(f))
    }
  }
  return m
}
const env = collect(/process\.env\.([A-Z][A-Z0-9_]+)/g, 1, (f) => !isTest(f))
for (const [k, v] of collect(/\b(?:str|int|bool|list|requiredIn)\(\s*(?:'production',\s*)?'([A-Z][A-Z0-9_]+)'/g, 1, (f) => f.endsWith('server/config.ts'))) {
  if (!env.has(k)) env.set(k, new Set())
  for (const f of v) env.get(k).add(f)
}
const storage = collect(/['"`]((?:sud|sb-cache)[-:][a-zA-Z0-9:_${}.-]*)['"`]/g, 1, (f) => !isTest(f))
const events = collect(/['"`](sud:[a-z-]+)['"`]/g, 1, (f) => !isTest(f))
const holders = collect(/\b(__[a-zA-Z]+)\b/g, 1, (f) => !isTest(f) && !f.includes('/app/layout'))

// ---- render ----------------------------------------------------------------------------------------------
const list = (set, n = 6) => {
  const a = [...set].map((f) => f.replace(/^src\//, ''))
  return a.slice(0, n).join(', ') + (a.length > n ? `, +${a.length - n}` : '')
}
const short = (f) => rel(f).replace(/^src\//, '')
let out = '<!-- GENERATED by scripts/gen-map.mjs — do not edit. Run `bun run map` after adding/moving files, routes, env vars, storage keys or events. -->\n'
out += '# Repo map — generated facts\n\nHand-written meaning, change recipes and duplicated-logic warnings: [MAP.md](./MAP.md).\n\n'

out += '## API routes\n\nEvery route is `guard()`-wrapped (tested in `src/server/__tests__/routes.test.ts`). `privileged` = needs the `x-sud-action` header (see SECURITY.md).\n\n| Path | Methods | What | File |\n|---|---|---|---|\n'
for (const r of routes) out += `| \`${r.path}\` | ${r.methods.join(', ')} | ${r.doc.replace(/\|/g, '/')} | \`${r.file.replace('src/app/api/', '')}\` |\n`

out += '\n## Who imports what (reverse index)\n\nRead this BEFORE changing a file: the right column is everything that can break. `tests:` lists the tests that import it (run those).\n\n'
const groups = [
  ['src/core/', 'Pure domain logic (`src/core`)'],
  ['src/server/', 'Server middleware / config / security'],
  ['src/sources/', 'Source adapters'],
  ['src/lib/', 'Libraries (`src/lib`)'],
  ['src/hooks/', 'Hooks'],
  ['src/infra/', 'Infra'],
  ['src/components/shell/', 'Shell'],
  ['src/components/proto/', 'Shared UI kit (`components/proto`)'],
  ['src/components/company/', 'Company header'],
  ['src/components/sections/', 'Company sections'],
  ['src/components/views/', 'Full-page views'],
  ['src/components/ui-custom/', 'UI helpers'],
]
for (const [prefix, title] of groups) {
  const fs = files.filter((f) => rel(f).startsWith(prefix) && !isTest(f) && !f.includes('/templates/'))
  if (!fs.length) continue
  out += `### ${title}\n\n| File | Imported by | Tests |\n|---|---|---|\n`
  for (const f of fs) {
    const users = importedBy.get(f)
    const tests = users.filter(isTest).map((t) => short(t))
    const prod = users.filter((u) => !isTest(u)).map((u) => short(u).replace(/^app\/api\//, 'api/').replace(/\/route\.ts$/, '/route'))
    const cell = prod.length ? prod.slice(0, 7).join(', ') + (prod.length > 7 ? `, +${prod.length - 7}` : '') : '(entry point / unused)'
    out += `| \`${short(f).replace(prefix.replace('src/', ''), '')}\` | ${cell} | ${tests.length ? tests.join(', ') : ''} |\n`
  }
  out += '\n'
}

out += '## Environment variables\n\n| Variable | Read in |\n|---|---|\n'
for (const k of [...env.keys()].sort()) if (!['NODE_ENV', 'NEXT_RUNTIME'].includes(k)) out += `| \`${k}\` | ${list(env.get(k), 4)} |\n`

out += '\n## Browser storage keys (localStorage / sessionStorage)\n\n| Key | Used in |\n|---|---|\n'
for (const k of [...storage.keys()].sort()) out += `| \`${k}\` | ${list(storage.get(k), 4)} |\n`

out += '\n## Custom window events\n\n| Event | Used in |\n|---|---|\n'
for (const k of [...events.keys()].sort()) out += `| \`${k}\` | ${list(events.get(k), 6)} |\n`

out += '\n## Server-side global holders (`globalThis.__x`, survive dev hot reloads)\n\n| Holder | Defined/used in |\n|---|---|\n'
for (const k of [...holders.keys()].sort()) out += `| \`${k}\` | ${list(holders.get(k), 4)} |\n`

if (process.argv.includes('--check')) {
  const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  if (cur !== out) {
    console.error('docs/MAP.generated.md is out of date — run `bun run map` and commit it.')
    process.exit(1)
  }
  console.log('docs/MAP.generated.md is up to date.')
} else {
  writeFileSync(OUT, out)
  console.log(`wrote ${rel(OUT)} (${out.length} bytes, ${routes.length} routes, ${files.length} files)`)
}
